version: "3.8"

services:
  spark:
    build: .
    container_name: pyspark-notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - PYSPARK_PYTHON=python3
    mem_limit: 2g
